### ISSUE TITLE
NoneType get

### ISSUE THREAD

**Issue by huseyinkozan** [faizshukri/terminator-layout-builder#4]
Now getting this err:
```bash
❯ tlb            
'NoneType' object has no attribute 'get'
```

Even with `-l` option:
```bash
❯ tlb -l l1                          
'NoneType' object has no attribute 'get'
```

**Comment by faizshukri** [comment]
It might be your YAML structure.

Can you show your `~/.config/terminator/layout.yaml` content?

**Comment by huseyinkozan** [comment]
```yaml
layoutA:
  - cmd: pwd

l1:
  - root: $HOME/p
    horizontal:
      panes:
        - vertical:
          panes:
            - cmd: "wd docker-yocto"
            - cmd: "cd huseyinkozan"
        - vertical:
          panes:
            - cmd: "pwd"
            - cmd: "pwd"
```

Yes, it seems I have a wrong yaml. After comment out `l1`, and run `tlb -l layoutA` it worked.

**Comment by huseyinkozan** [comment]
How can we add pane without cmd, or exec cmd after some time ? 
Zsh takes some time to load.

**Comment by faizshukri** [comment]
Your indentation was slightly off, making yaml format incorrect.

```yaml
layoutA:
  - cmd: pwd

l1:
  - root: $HOME/p
    horizontal:
      panes:
        - vertical:
            panes: # <- this need to be indented
              - cmd: "wd docker-yocto"
              - cmd: "cd huseyinkozan"
        - vertical:
            panes: # <- this need to be indented
              - cmd: "pwd"
              - cmd: "pwd"

```

---

> How can we add pane without cmd, or exec cmd after some time ?
> Zsh takes some time to load.

If you want to add delay to cmd, use `sleep <seconds>; <command>`
