### ISSUE TITLE
'Maximized' option ignored.

### ISSUE THREAD

**Issue by laraconda** [faizshukri/terminator-layout-builder#8]
If I write

```
layout:
  # A window
  - root: $HOME/dir # root for this window
    maximized: true
    horizontal:
      panes:
        - title: "title1"
        - title: "title2"
```
then the produced code does not include the "maximized" option.
